// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2TD8JTncRMVdNEnA0l5MxM6NNfwfHhWY',
    appId: '1:832456276581:web:7386c409c8b91a1890e48c',
    messagingSenderId: '832456276581',
    projectId: 'collaborative-notes-app',
    authDomain: 'collaborative-notes-app.firebaseapp.com',
    storageBucket: 'collaborative-notes-app.appspot.com',
    measurementId: 'G-3Q41Y8QE5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3stlMwrsw4BNTJVcQTWkzqFv5RGPV0Lc',
    appId: '1:832456276581:android:8daed87f9306dc9490e48c',
    messagingSenderId: '832456276581',
    projectId: 'collaborative-notes-app',
    storageBucket: 'collaborative-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKREeYRoAplDlM-V-W14n_tqOeTOe6L5s',
    appId: '1:832456276581:ios:6aa94c8403178ea590e48c',
    messagingSenderId: '832456276581',
    projectId: 'collaborative-notes-app',
    storageBucket: 'collaborative-notes-app.appspot.com',
    iosBundleId: 'com.example.collaborativeNotesApp',
  );

}